### ISSUE TITLE
Serif Semibold Italic appears to be a sans, not a serif

### ISSUE THREAD

**Issue by JoeArizona** [khaledhosny/libertinus#48] opened 2016-11-16 18:27 UTC
Hi Khaled – This is what I see when I open the Serif Semibold Italic:

![libertinus serif sans mixup](https://cloud.githubusercontent.com/assets/8071692/20360029/76f73a10-abef-11e6-96d1-e0fd5fe277f0.PNG)

It's the only serif that looks like this, the only one that looks like a sans.

**Comment by khaledhosny** [comment] 2016-11-18 16:32
What version of Windows is this? Looks like it is not loading the font all in the waterfall, the lines above it look fine.

**Comment by fitojb** [comment] 2016-12-29 12:00
Isn’t this something Microsoft should fix?

**Comment by khaledhosny** [comment] 2016-12-29 12:13
It might be a bug in the fonts, but I need more information.

**Comment by khaledhosny** [comment] 2017-02-15 16:59
@JoeArizona is this still an issue for you?

**Comment by JoeArizona** [comment] 2017-02-17 10:37
Ah, sorry I missed the replies. This is Windows 10 64-bit Home. I'll retest later today.

**Comment by JoeArizona** [comment] 2017-02-17 12:26
Okay, it looks like this only happens on the font install screen, which normally displays the actual glyphs of the font to be installed (in the waterfall). For some reason, it's displaying a sans font for the serif semibold italic. However, **once installed the font displays correctly in apps like MS Word 2016.**

By contrast, serif **regular** italic displays fine in the install window (the waterfall):

![2017-02-17_05-04-41](https://cloud.githubusercontent.com/assets/8071692/23065129/2f35eb10-f4d1-11e6-8e0d-cd8c7b46aa92.png)

I think all the other versions also display fine in the install screen. There's just something going on with the serif semibold italic file that is causing its problem – maybe something's up with the headers or glyf tables?

**Comment by khaledhosny** [comment] 2017-02-17 13:32
I can reproduce this in the font viewer as well, but for the smaller sizes not the bigger ones. Looking into it.

**Comment by khaledhosny** [comment] 2017-02-17 14:17
I can’t reproduce the issue with any other application, nor I’m able to find any thing special in this font file that might cause this. Closing as it seems just a minor annoyance.

**Closed by khaledhosny** 2017-02-17 14:17 UTC
Labels: question
