### ISSUE TITLE
Housekeeping

### ISSUE THREAD

**Issue by davelab6** [khaledhosny/libertinus#13] opened 2016-01-28 22:01 UTC
I offer these suggestions
- [x] GPL: Well, pedantic I am :) I suggest to drop it, its rather useless for fonts because it may require documents to be GPL compatible also, and should be discouraged 
- [x] Changelog.libertine: rename to `FONTLOG.linuxlibertine.txt`
- [x] LICENSE.txt: drop it
- [x] README.linuxlibertine: append `.txt`
- [ ] remove binaries from the repo root, only distribute them via release zips
- [x] OFL.txt put the copyright notices all on 1 line, so they match the copyright string inside the sources

**Comment by khaledhosny** [comment] 2016-01-29 07:46
`Changelog` was the original file name, but I don’t mind renaming it for uniformity.

I’m keeping the binaries under version on control, though. I used not to do that, but I have no confidence in the reproducibility of the build with the current tool chain, so I like to keep the binaries in case I want to bisect some issue, also keeping the binaries make the bisect faster. The other reason is that I often want people to test fixes against master, and it is a lot easier to always have the binary than to distribute special builds on ad-hook bases.

**Comment by alerque** [comment] 2016-01-29 08:00
One alternative is to create another branch with a detatched root to keep the binaries in (the same idea that GitHub uses with the gh-pages branch). Depending on how your local toolchain is setup you could even have the fonts build and get committed to that  branch in a post-commit hook from the source branch. This would keep the master branch free of binary blobs but still allow you to use fast git-bisects to test issues without having to either re-compile or match up tallballs. It also makes it easy to download pre-compiled fonts from git HEAD, but without the pollution in master.

**Comment by khaledhosny** [comment] 2016-01-29 08:11
Since the main argument against keeping the binaries in the git repo is to decrease repository size, a different branch will not help while complicating my build setup. Alternatively one can use a different git repo as a sumbodule, but I like to keep the simplicity of the current setup until there is a compelling reason to do otherwise.

**Comment by alerque** [comment] 2016-01-29 08:36
Having the binaries is a separate branch would help the size thing. People cloning it for the source would not have to download the entire binary history. Currently cloning defaults to fetching commits from all branches, but `git clone --single-branch` is an option and likely to be the default at some point in the future.

Another trick that would minimize the complication to your build setup is `git worktree`. You can check out a branch into a subfolder so that you can work on both sets of files at  once. For example you could have a "dist" branch with _only_ the binary builds. `git worktree add dist dist` would checkout the dist branch into a dist folder, then you'd be looking at both the source and the binary files side by side, but they would actually be tracked in different branches.

**Comment by khaledhosny** [comment] 2016-01-29 15:46
Not really convinced that there is much value in cloning this repo without the binaries, given how hard to replicate the current build toolchain (even for me), but re-opening for now to think about this a bit more.

**Comment by davelab6** [comment] 2016-01-29 15:59
On 29 January 2016 at 03:36, Caleb Maclennan <notifications@github.com>
wrote:

> Having the binaries is a separate branch would help the size thing. People
> cloning it for the source would not have to download the entire binary
> history. Currently cloning defaults to fetching commits from all branches,
> but git clone --single-branch is an option and likely to be the default
> at some point in the future.
>
> Another trick that would minimize the complication to your build setup is git
> worktree. You can check out a branch into a subfolder so that you can
> work on both sets of files at once. For example you could have a "dist"
> branch with *only* the binary builds. git worktree add dist dist would
> checkout the dist branch into a dist folder, then you'd be looking at both
> the source and the binary files side by side, but they would actually be
> tracked in different branches.
>
I think that is an invaluable tip! Thank you Caleb!

**Comment by khaledhosny** [comment] 2017-02-15 17:28
Too much work, too little benefit for me. One day we will have a reproducible build system and the binaries will not be needed, one day.

**Closed by khaledhosny** 2017-02-15 17:28 UTC
Labels: enhancement
